name: Moodle Scraper

on:
  schedule:
    - cron: '0 8 * * *' #8Uhr UTC
  workflow_dispatch:

jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.3'
      
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
      
      - name: Install Playwright Browsers
        run: playwright install chromium --with-deps
        
      - name: Run Scraper
        env: 
          tuOTP: ${{ secrets.TUOTP}}
          tuUsername: ${{ secrets.TUUSERNAME}}
          tuPassword: ${{ secrets.TUPASSWORD}}
          notionSecret: ${{ secrets.NOTIONSECRET}}
          notionID: ${{ secrets.NOTIONID}}
          notionVersion: ${{ secrets.NOTIONVERSION}}
          modulDbId: ${{ secrets.MODULDBID}}
        run: python main.py
